all:
  vars:
    # This is your SSH public key, e.g. cat ~/.ssh/id_rsa.pub
    ssh_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC47skp+COmqBQep6sNtXi+cMclZvdrvyz7RUqc3vcGNpttUBDwTLMVp66LkwPL5XJjNTWhtcKiBnuG0EPs5ha9/98iIVmXcy2z/PqyjWZLggH7CNQ+iPKOM+3Z6fHIPY72EMtoRdKojwfWBcLGBur7BInI7xFa/3VA9OY79kCKJhUB6IAzuCVWpW56j3BWIBBj/J2wHUYIU71fx95KAHWK6X8zeyMx5xqtmjb8ed1J54n05iDknEVBiznn/gTFLBA5r+KBvNYKXWXsZUjKmirHvCTcOwctW5kKjHqXud1bMfyYAw4E5N/yuhjDfQEqrUDLaQ3Tikd3l0YiFRckKwwV0GTlsCbcMkmwAUwBv0g91p4PkNelV4RjYxAwBn5r8E01xQRIkzmHTPVKiali9B6TQiYgbIgCb5wYHOeRU8NguAvn49S9SxPr3E7tgmZH19eNa7ucmHp6XhHQ9C687IXIZ/ACSBE2vqLlUwLKIP60j0orgEAyUi86Z/lyjim/hoc= trbiv@pop-os"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKGh+oJtz1BAEpGErOvDrKoLiW9NPID5TVM7tFyh5gaDlKksvLmBIS/VXNvsdZj27GTAqOzQGZ3SfDz+CRbxmUpQZrZyhrrFM1EFYrwpeCXiQ79Uih+98Y8efWaW/0SEy3qwXonEucpU4epbYAvDNlc5ou+uUJIcYYZ4SbegQGaGwjGq2pMfcEKdexO6Z/OM0cTnrQ7JMzmY3ga1vMl4/rCh0sDbIR6rSTsgnDma4UrnkaL9UNXzK+HnhhvGe8okqxqAOwh/UeS4ruknngstdYjolMxWD5F4q0AwsNf1I59DOw2cVhh1DgcM1HAh25l5J7T2pWNMM2oh/11Rp6D+Tx6M4MNwgZ9TCPkFCgFAalipIdx0XRQY2nTk7WzSOl/Eo56n9/z95VcMpOp+OQaSYNjxy7lJE8PzPmpVmwFMU1R5dkDqjdtE/2DWJYNY/+Seg39qwy+qybOcnDGe99pt9ePBWwOSuMzKlxn+oTf3u8CEzuX2YlOkY/ksxkqySzpFE= satoshi@nakamoto"
    # The username you want to use to login to those machines (and your public key will be added to).
    user: satoshi
    # The initial username to login with, for fresh nodes that may not have your username setup.
    ansible_user: satoshi
    # The default validator each GPU worker node will be assigned to.
    validator: 5Dt7HZ7Zpw4DppPxFM7Ke3Cm7sDAWhsZXmM5ZAmE7dSVJbcQ
    # By default, no nodes are the primary (CPU node running all the apps, wireguard, etc.) Override this flag exactly once below.
    is_primary: false
    # We assume GPU is enabled on all nodes, but of course you need to disable this for the CPU nodes below.
    gpu_enabled: true
    # The port you'll be using for the registry proxy, MUST MATCH chart/values.yaml registry.service.nodePort!
    registry_port: 30500
    # SSH sometimes just hangs without this...
    ansible_ssh_common_args: '-o ControlPath=none'
    # SSH retries...
    ansible_ssh_retries: 3
    # Ubuntu major/minor version.
    ubuntu_major: "22"
    ubuntu_minor: "04"
    # CUDA version - leave as-is unless using h200s, in which case either use 12-5 or skip_cuda: true (if provider already pre-installed drivers)
    cuda_version: "12-6"
    # NVIDA GPU drivers - leave as-is unless using h200s, in which case it would be 555
    nvidia_version: "560"
    # Flag to skip the cuda install entirely, if the provider already has cuda 12.x+ installed (note some chutes will not work unless 12.6+)
    skip_cuda: false
    # Flag to enable/disable IPv6. Some hosts may require IPv6 to be on.
    ipv6_enabled: true
    # Default MTU
    wireguard_mtu: 1380

  hosts:
    chutes-manager:
      ansible_host: 50.237.5.44 
      external_ip: 50.237.5.44
      wireguard_ip: 192.168.0.1 
      gpu_enabled: false
      is_primary: true

    # 4090 enabled VMs
    chutes-4090-0:
      ansible_host: 50.237.5.41 
      external_ip: 50.237.5.41
      wireguard_ip: 192.168.0.3 
    chutes-4090-1:
      ansible_host: 50.237.5.42 
      external_ip: 50.237.5.42
      wireguard_ip: 192.168.0.4 
    chutes-4090-2:
      ansible_host: 50.237.5.43 
      external_ip: 50.237.5.43
      wireguard_ip: 192.168.0.5 
