- name: Join all nodes to the kubernetes cluster
  hosts: all
  tasks:
    - name: Check if node is already part of cluster
      shell: microk8s status | grep "acting as a node in a cluster"
      register: cluster_check
      failed_when: false
      changed_when: false
      when: not is_primary | bool

    - name: Get cluster join command
      shell: microk8s add-node --token-ttl 600
      register: join_command
      when: is_primary | bool

    - name: Extract join string
      set_fact:
        join_string: "{{ join_command.stdout | regex_search('microk8s join 10.2[^ ]+') }}"
      when: is_primary | bool

    - name: Share join command with other plays
      set_fact:
        join_command: "{{ join_string }}"
      delegate_to: localhost
      delegate_facts: true
      when: is_primary | bool

    - name: Join cluster as worker node
      shell: "{{ hostvars['localhost']['join_command'] | replace('\n', '') }} --worker --skip-verify"
      when:
        - not is_primary | bool
        - cluster_check.rc != 0

    - name: Wait for node to be ready
      shell: "microk8s kubectl get nodes --no-headers | grep -w Ready"
      register: node_ready
      until: node_ready.rc == 0
      retries: 30
      delay: 10
      when: is_primary | bool
      loop: "{{ groups['all'] }}"

    - name: Label nodes with external IP
      shell: "microk8s kubectl label nodes {{ item }} chutes/external-ip={{ hostvars[item].external_ip }} --overwrite"
      when: is_primary | bool
      loop: "{{ groups['all'] }}"
